# Generated by Django 5.2.6 on 2025-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phonenum', models.FloatField(max_length=100)),
            ],
        ),
    ]
